from src.genetic_algorithm import *
import matplotlib.pyplot as plt


def main():
    graph, adj_list, _, _ = create_complete_graph(extended_output=True)
    # print(graph[0])
    # print(adj_list["train"]["cost"])
    # print(adj_list["train"]["johnson"])
    # print(graph[2])
    # print(graph[3])
    j1 = johnson(graph, "train", "cost")
    # print()
    # for elem, d in j1.items(): print(elem, d[0], d[1])
    # print()
    # save_graph_to_file(graph, "data/test1.csv")
    # new_graph = load_graph_from_file("data/test1.csv")
    # j1 = johnson(new_graph, "train", "cost")
    # print()
    # for elem, d in j1.items(): print(elem, d[0], d[1])
    # print()
    # print(new_graph.nodes(data=True))
    # print(str(graph.nodes(data=True)) == str(new_graph.nodes(data=True)))
    # print(str(graph.edges(data=True)) == str(new_graph.edges(data=True)))
    g1 = Gene("xD1", 10, "car")
    g2 = Gene("xD2", 20, "car")
    g3 = Gene("xD3", 30, "train")
    g4 = Gene("xD4", 11, "train")
    g5 = Gene("xD5", 21, "train")
    g6 = Gene("xD6", 31, "train")
    g7 = Gene("xD5", 22, "train")
    gx = g1
    g1.mode_of_transit = "plane"
    # print(g1.mode_of_transit)
    ch1 = Chromosome([g1, g2, g3])
    # for elem in ch1:
    # print(elem)
    # print(ch1[0])
    # ch1[0] = g2
    # print(ch1)
    ch1[0] = g4
    # print(ch1)
    ch1.insert(0, g1)
    # print(ch1)
    ch1.append(g6)
    # print(ch1)
    ch1.pop(1)
    # print(ch1)
    ch1[0].date = 50
    # print(ch1)
    gen1 = Genotype([deepcopy(ch1), deepcopy(ch1)])
    # org1 = Organism(gen1)
    # print(org1)
    # org1.mutate(MutationType.TRANSIT_MODE)
    # print(org1)
    package_list = [{"city_from": "xD1", "city_to": "xD2", "date_ready": 1, "date_delivery": 2, "weight": 10},
                    {"city_from": "xD3", "city_to": "xD4", "date_ready": 3, "date_delivery": 4, "weight": 20}]
    # save_list_to_file(package_list, "data/test2.csv")
    # new_list = load_list_from_file("data/test2.csv")
    # print(package_list)
    # print(new_list)

    """g1 = Gene("C", 1, "car")
    g2 = Gene("B", 2, "train")
    ch1 = Chromosome([g1, g2])
    g1 = Gene("C", 4, "plane")
    ch2 = Chromosome([g1])
    g1 = Gene("A", 6, "train")
    g2 = Gene("B", 8, "plane")
    ch3 = Chromosome([g1, g2])
    gen1 = Genotype([ch1, ch2, ch3])

    tprob = TransportProblemObject("data/simple3_graph.csv", "data/simple3_list.csv")
    org1 = Organism(gen1, tprob)
    print(org1)
    cost1 = tprob.evaluate_function(org1)
    print(cost1)

    org1.mutate(MutationType.DATE)
    print(org1)
    cost1 = tprob.evaluate_function(org1)
    print(cost1)"""

    """g1 = Gene("F", 1, "car")
    g2 = Gene("D", 3, "train")
    ch1 = Chromosome([g1, g2])
    g1 = Gene("C", 7, "plane")
    ch2 = Chromosome([g1])
    g1 = Gene("E", 4, "plane")
    g2 = Gene("A", 5, "plane")
    g3 = Gene("B", 6, "car")
    ch3 = Chromosome([g1, g2, g3])
    g1 = Gene("F", 7, "car")
    g2 = Gene("A", 9, "train")
    ch4 = Chromosome([g1, g2])
    g1 = Gene("F", 6, "plane")
    ch5 = Chromosome([g1])
    g1 = Gene("B", 9, "train")
    g2 = Gene("E", 11, "plane")
    ch6 = Chromosome([g1, g2])
    g1 = Gene("B", 7, "plane")
    ch7 = Chromosome([g1])
    g1 = Gene("C", 9, "car")
    ch8 = Chromosome([g1])
    g1 = Gene("D", 6, "plane")
    ch9 = Chromosome([g1])
    g1 = Gene("F", 11, "train")
    ch10 = Chromosome([g1])
    g1 = Gene("A", 12, "train")
    ch11 = Chromosome([g1])
    g1 = Gene("E", 14, "car")
    ch12 = Chromosome([g1])
    gen1 = Genotype([ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, ch9, ch10, ch11, ch12])

    tprob = TransportProblemObject("data/simple6_graph.csv", "data/simple6_list.csv")
    org1 = Organism(gen1, tprob)
    print(org1)
    cost1 = tprob.evaluate_function(org1)
    print(cost1)

    org1.mutate(MutationType.DELETE_GENE)
    print(org1)
    cost1 = tprob.evaluate_function(org1)
    print(cost1)"""

    g1 = Gene("F", 1, "train")
    g2 = Gene("D", 7, "train")
    ch1 = Chromosome([g1, g2])
    g1 = Gene("C", 7, "train")
    ch2 = Chromosome([g1])
    g1 = Gene("E", 4, "train")
    g2 = Gene("A", 5, "train")
    g3 = Gene("B", 6, "train")
    ch3 = Chromosome([g1, g2, g3])
    g1 = Gene("F", 3, "train")
    g2 = Gene("A", 6, "train")
    ch4 = Chromosome([g1, g2])
    g1 = Gene("F", 6, "train")
    ch5 = Chromosome([g1])
    g1 = Gene("B", 6, "train")
    g2 = Gene("E", 10, "train")
    ch6 = Chromosome([g1, g2])
    g1 = Gene("B", 7, "train")
    ch7 = Chromosome([g1])
    g1 = Gene("C", 9, "train")
    ch8 = Chromosome([g1])
    g1 = Gene("D", 6, "train")
    ch9 = Chromosome([g1])
    g1 = Gene("F", 11, "train")
    ch10 = Chromosome([g1])
    g1 = Gene("A", 12, "train")
    ch11 = Chromosome([g1])
    g1 = Gene("E", 13, "train")
    ch12 = Chromosome([g1])
    gen1 = Genotype([ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, ch9, ch10, ch11, ch12])

    g1 = Gene("C", 4, "car")
    g2 = Gene("D", 8, "car")
    ch1 = Chromosome([g1, g2])
    g1 = Gene("C", 7, "car")
    ch2 = Chromosome([g1])
    g1 = Gene("E", 4, "car")
    g2 = Gene("A", 5, "car")
    g3 = Gene("B", 6, "car")
    ch3 = Chromosome([g1, g2, g3])
    g1 = Gene("F", 7, "car")
    g2 = Gene("A", 9, "car")
    ch4 = Chromosome([g1, g2])
    g1 = Gene("F", 6, "car")
    ch5 = Chromosome([g1])
    g1 = Gene("B", 8, "car")
    g2 = Gene("E", 10, "car")
    ch6 = Chromosome([g1, g2])
    g1 = Gene("B", 7, "car")
    ch7 = Chromosome([g1])
    g1 = Gene("C", 9, "car")
    ch8 = Chromosome([g1])
    g1 = Gene("D", 6, "car")
    ch9 = Chromosome([g1])
    g1 = Gene("F", 15, "car")
    ch10 = Chromosome([g1])
    g1 = Gene("A", 12, "car")
    ch11 = Chromosome([g1])
    g1 = Gene("E", 14, "car")
    ch12 = Chromosome([g1])
    gen2 = Genotype([ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, ch9, ch10, ch11, ch12])

    tprob = TransportProblemObject("data/simple6_graph.csv", "data/simple6_list.csv")
    org1 = Organism(gen1, tprob)
    # print(org1)
    cost1 = tprob.evaluate_function(org1)
    print(cost1)
    org2 = Organism(gen2, tprob)
    # print(org2)
    cost2 = tprob.evaluate_function(org2)
    print(cost2)

    children_costs = []
    children = []
    for _ in range(1000):
        org3 = org1.crossover(org2, "random_selection")
        # print(org3)
        cost3 = tprob.evaluate_function(org3)
        # print(cost3)
        children_costs.append(cost3)
        children.append(org3)
    print(len(children_costs) - children_costs.count(INF), "/", len(children_costs))
    print(min(children_costs))
    print()

    org3 = org1.crossover(org2, "random_selection")
    min_cost = tprob.evaluate_function(org3)
    print(min_cost)
    inf_cnt = 0
    muts = [elem for elem in MutationType]
    for _ in range(1000):
        mut = muts[randint(0, len(muts) - 1)]
        tmp_org = deepcopy(org3)
        tmp_org.mutate(mut)
        cost3 = tprob.evaluate_function(tmp_org)
        if cost3 == INF:
            inf_cnt += 1
        if cost3 < min_cost:
            min_cost = cost3
            # print(min_cost)
    print(min_cost)
    print((1000 - inf_cnt), "/", 1000)
    print()

    pop1 = Population(children[:4])
    save_population_to_file(pop1,"data/simple6_population.csv")
    pop2 = Population("data/simple6_population.csv")
    pop2.link_problem(tprob)
    print(pop1[3])
    print(pop1[3].cost())
    print(pop2[3])
    print(pop2[3].cost())
    print()
    selection = pop1.selection("ranking", 0.5)
    for elem in pop1: print(elem.cost(), end=" ")
    print()
    print(selection)
    pop1.reproduction(selection, ["random_selection"], ["city", "date", "transit_mode"], 0.5)
    for elem in pop1: print(elem.cost(), end=" ")
    print()
    print()

    inf_cnt = 0
    min_cost = INF
    for _ in range(1000):
        org4 = tprob.generate_solution()
        org4.evaluate()
        cost4 = org4.cost()
        if cost4 == INF:
            inf_cnt += 1
        if cost4 < min_cost:
            min_cost = cost4
            # print(min_cost)
    print(min_cost)
    print((1000 - inf_cnt), "/", 1000)
    print()

    l1 = generate_package_list(tprob.graph, 12, (5,10), 18, 3)
    for elem in l1: print(elem)
    print()

    extra_data = {}
    best_one = genetic_algorithm(tprob, "data/test_config.json", extra_data)
    print(best_one)

    vx = [i for i in range(len(extra_data["best_overall"]))]
    plt.plot(vx, extra_data["best_overall"], "r-")
    plt.plot(vx, extra_data["mean_in_iter"], "b-")
    plt.legend(["best_overall", "mean_in_iter"])
    plt.show()


if __name__ == '__main__':
    main()
